#!/usr/bin/env ruby

$: << File.expand_path(File.dirname(__FILE__) + "/../lib")
require 'fileutils'
require 'rubygems'
require 'optparse'
require 'kodiak'


@options = {}

OptionParser.new do |opts|
  opts.on("-f", "--force", "Force") do |option|
  	@options[:force] = option
  end
  opts.on("-q", "--quiet", "Quiet") do |option|
  	@options[:quiet] = option
  end
end.parse!


# giddy up
case ARGV.first
when 'generate'
	Kodiak::Generator.new(@options).generate	
when 'push'
	Kodiak::push(@options)
when 'watch'
	Kodiak::watch(@options)
else
	Kodiak::usage
end
