# Example environments
# local:
#   files:
#     'src/javascript/application.js' : 'public/scripts/application.js'
#     'src/css/screen.css'            : 'public/css/screen.css'
#     
# remote:
#   ftp: true
#   server  : 'example.com'
#   username: 'admin'
#   password: 'abc123'
#   path    : '/public_html/'
#   files:
#     'src/javascript/application.js'  : 'public/scripts/application.js'
#     'src/css/screen.css'            : 'public/css/screen.css'

#########################################################################################

# You can name your environments how you wish. 'local' and 'remote' are just examples.
# Once your environments are defined, you can call them from the command line
# ex: kodiak push local

#########################################################################################













